"""
model_comparison.py
===================

Compares three regression models for Green ICT corrective-action
prioritization:

1. Random Forest
2. Gaussian Process
3. Gradient Boosting

The models use the same feature representation and TOPSIS reference
target generated by ai_ranker.py.

Selection rule:
    The model with the lowest mean 5-fold cross-validation MAE
    is selected as the primary regression model.

Current decision-support model:
    8 consolidated corrective actions (A01-A08)
    8 consolidated gaps (G01-G08)
"""


import csv
from pathlib import Path

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
)

from sklearn.gaussian_process import (
    GaussianProcessRegressor,
)

from sklearn.gaussian_process.kernels import (
    RBF,
    ConstantKernel,
)

from sklearn.model_selection import (
    KFold,
    cross_val_score,
)

from ai_ranker import (
    build_feature_table,
    _augment,
)


# ============================================================
# PATH CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

OUTPUT_FILE = (
    BASE_DIR / "model_comparison_results.csv"
)


# ============================================================
# MODEL DEFINITIONS
# ============================================================

def get_models():
    """
    Return the three candidate regression models.
    """

    return {

        # ----------------------------------------------------
        # 1. Random Forest
        # ----------------------------------------------------

        "Random Forest": RandomForestRegressor(
            n_estimators=300,
            max_depth=8,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=1,
        ),

        # ----------------------------------------------------
        # 2. Gaussian Process
        # ----------------------------------------------------

        "Gaussian Process": GaussianProcessRegressor(

            kernel=(
                ConstantKernel(
                    1.0,
                    (1e-2, 1e2),
                )
                *
                RBF(
                    length_scale=1.0,
                    length_scale_bounds=(
                        1e-2,
                        1e2,
                    ),
                )
            ),

            alpha=1e-3,

            normalize_y=True,

            random_state=42,

            optimizer=None,
        ),

        # ----------------------------------------------------
        # 3. Gradient Boosting
        # ----------------------------------------------------

        "Gradient Boosting": GradientBoostingRegressor(
            n_estimators=200,
            max_depth=4,
            learning_rate=0.05,
            random_state=42,
        ),
    }


# ============================================================
# MODEL SELECTION
# ============================================================

def select_best_model(results):
    """
    Select the regression model with the lowest mean
    cross-validation MAE.

    Lower MAE indicates lower average absolute
    prediction error.
    """

    valid = [
        result
        for result in results
        if result["cv_mae"] is not None
    ]

    if not valid:

        raise RuntimeError(
            "No regression model completed successfully."
        )

    return min(
        valid,
        key=lambda result: result["cv_mae"],
    )


# ============================================================
# MODEL COMPARISON
# ============================================================

def compare_models(
    cv_folds=5,
    seed=42,
):
    """
    Train and evaluate all three candidate models using
    K-fold cross-validation.

    Returns:
        List of model evaluation results sorted by CV MAE.
    """

    # --------------------------------------------------------
    # Build feature table
    # --------------------------------------------------------

    records, X, y_ref, weights, ahp_info = (
        build_feature_table()
    )

    # --------------------------------------------------------
    # Validate the number of consolidated actions
    # --------------------------------------------------------

    action_count = len(records)

    print(
        f"Original corrective actions: "
        f"{action_count}"
    )

    if action_count != 8:

        raise ValueError(
            "Expected 8 consolidated corrective actions "
            f"(A01-A08), but found {action_count}. "
            "Check action_rules.csv, priority_rules.csv, "
            "and gap_analysis.csv."
        )

    # --------------------------------------------------------
    # Generate augmented training dataset
    # --------------------------------------------------------

    Xa, ya = _augment(
        X,
        weights,
    )

    print(
        f"Augmented observations: "
        f"{len(Xa)}"
    )

    print(
        "Expected observations: "
        "2408 "
        "(8 original + 2400 synthetic)"
    )

    # --------------------------------------------------------
    # K-fold cross-validation
    # --------------------------------------------------------

    kf = KFold(
        n_splits=cv_folds,
        shuffle=True,
        random_state=seed,
    )

    results = []

    models = get_models()

    print()

    print(
        f"Evaluating {len(models)} candidate models "
        f"using {cv_folds}-fold cross-validation..."
    )

    # --------------------------------------------------------
    # Evaluate every candidate model
    # --------------------------------------------------------

    for name, model in models.items():

        print(
            f"  Evaluating: {name} ...",
            end=" ",
            flush=True,
        )

        try:

            # ------------------------------------------------
            # Mean Absolute Error
            # ------------------------------------------------

            mae_scores = -cross_val_score(
                model,
                Xa,
                ya,
                cv=kf,
                scoring="neg_mean_absolute_error",
                n_jobs=1,
            )

            # ------------------------------------------------
            # R-squared
            # ------------------------------------------------

            r2_scores = cross_val_score(
                model,
                Xa,
                ya,
                cv=kf,
                scoring="r2",
                n_jobs=1,
            )

            # ------------------------------------------------
            # Store results
            # ------------------------------------------------

            result = {

                "model":
                    name,

                "cv_mae":
                    float(
                        mae_scores.mean()
                    ),

                "cv_mae_std":
                    float(
                        mae_scores.std()
                    ),

                "cv_r2":
                    float(
                        r2_scores.mean()
                    ),

                "cv_r2_std":
                    float(
                        r2_scores.std()
                    ),
            }

            results.append(result)

            print(
                f"done "
                f"(MAE={result['cv_mae']:.4f}, "
                f"R²={result['cv_r2']:.4f})"
            )

        except Exception as exc:

            print(
                f"FAILED: {exc}"
            )

            results.append({

                "model":
                    name,

                "cv_mae":
                    None,

                "cv_mae_std":
                    None,

                "cv_r2":
                    None,

                "cv_r2_std":
                    None,
            })

    # --------------------------------------------------------
    # Separate successful and failed models
    # --------------------------------------------------------

    valid = [
        result
        for result in results
        if result["cv_mae"] is not None
    ]

    failed = [
        result
        for result in results
        if result["cv_mae"] is None
    ]

    # --------------------------------------------------------
    # Sort successful models by MAE
    # Lower MAE = better according to the predefined rule.
    # --------------------------------------------------------

    valid.sort(
        key=lambda result:
        result["cv_mae"]
    )

    return valid + failed


# ============================================================
# CONSOLE OUTPUT
# ============================================================

def format_console(results):
    """
    Print the model-comparison table and selected model.
    """

    print()

    print("=" * 82)

    print(
        "MODEL COMPARISON — "
        "5-FOLD CROSS-VALIDATION"
    )

    print("=" * 82)

    print(
        f"{'Model':<22}"
        f"{'CV MAE':>11}"
        f"{'± Std':>9}"
        f"{'CV R²':>9}"
        f"{'± Std':>9}"
    )

    print("-" * 82)

    for result in results:

        if result["cv_mae"] is None:

            print(
                f"{result['model']:<22}"
                f"{'FAILED':>11}"
            )

        else:

            print(
                f"{result['model']:<22}"
                f"{result['cv_mae']:>11.4f}"
                f"{result['cv_mae_std']:>9.4f}"
                f"{result['cv_r2']:>9.4f}"
                f"{result['cv_r2_std']:>9.4f}"
            )

    print("=" * 82)

    # --------------------------------------------------------
    # Select best model
    # --------------------------------------------------------

    valid = [
        result
        for result in results
        if result["cv_mae"] is not None
    ]

    if not valid:

        print(
            "\nNo model was successfully evaluated."
        )

        return None

    best = select_best_model(
        results
    )

    print()

    print(
        "Selection rule:"
    )

    print(
        "The model with the lowest mean "
        "5-fold CV MAE is selected as "
        "the primary regression model."
    )

    print()

    print(
        f"Selected model: "
        f"{best['model']}"
    )

    print(
        f"CV MAE: "
        f"{best['cv_mae']:.4f}"
    )

    print(
        f"CV MAE Std: "
        f"{best['cv_mae_std']:.4f}"
    )

    print(
        f"CV R²: "
        f"{best['cv_r2']:.4f}"
    )

    print(
        f"CV R² Std: "
        f"{best['cv_r2_std']:.4f}"
    )

    return best


# ============================================================
# CSV EXPORT
# ============================================================

def export_csv(
    results,
    filename=OUTPUT_FILE,
):
    """
    Save model-comparison results to CSV for
    reporting and paper preparation.
    """

    fieldnames = [

        "model",

        "cv_mae",

        "cv_mae_std",

        "cv_r2",

        "cv_r2_std",
    ]

    with Path(filename).open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        writer.writerows(
            results
        )

    print()

    print(
        f"Saved: {filename}"
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    print(
        "=" * 82
    )

    print(
        "GREEN ICT REGRESSION MODEL COMPARISON"
    )

    print(
        "=" * 82
    )

    print()

    print(
        "Decision-support configuration:"
    )

    print(
        "  Consolidated gaps: G01-G08"
    )

    print(
        "  Corrective actions: A01-A08"
    )

    print(
        "  Candidate models: 3"
    )

    print(
        "  Cross-validation: 5-fold"
    )

    print()

    print(
        "Running model comparison..."
    )

    print(
        "(This may take some time.)"
    )

    print()

    # --------------------------------------------------------
    # Run comparison
    # --------------------------------------------------------

    results = compare_models(
        cv_folds=5,
        seed=42,
    )

    # --------------------------------------------------------
    # Display results and select model
    # --------------------------------------------------------

    best_model = format_console(
        results
    )

    # --------------------------------------------------------
    # Export results
    # --------------------------------------------------------

    export_csv(
        results
    )

    # --------------------------------------------------------
    # Final output
    # --------------------------------------------------------

    print()

    print("=" * 82)

    if best_model is not None:

        print(
            f"Final selected model: "
            f"{best_model['model']}"
        )

        print(
            f"Final CV MAE: "
            f"{best_model['cv_mae']:.4f}"
        )

    else:

        print(
            "No model was selected."
        )

    print("=" * 82)